### ISSUE TITLE
Ethernet does not work if uC starts with the cable disconnected

### ISSUE THREAD

**Issue by rtek1000** [stm32duino/LwIP#4] opened 2020-03-06 17:06 UTC
Hello, i would like to report a problem, i got around, but it may be necessary to find another better alternative.

https://community.st.com/s/question/0D50X0000CDolzDSQR/ethernet-does-not-work-if-uc-starts-with-the-cable-disconnected

**Comment by fpistm** [comment] 2020-03-09 06:37
Hi @rtek1000 
thnaks.
I close this one as it is a duplicate of this one:
https://github.com/stm32duino/STM32Ethernet/issues/42

**Closed as completed by fpistm** 2020-03-09 06:37 UTC
Labels: duplicate
